---
- name: 'Include tasks to ensure variables are defined properly'
  ansible.builtin.include_tasks:
    file: 'assert.yml'

- name: 'Include tasks to configure firewalld'
  ansible.builtin.include_tasks:
    file: 'firewalld.yml'
  when: >-
    (
      _sat_firewalld_ports is defined
      and _sat_firewalld_ports | length > 0
    ) or (
      _sat_firewalld_services is defined
      and _sat_firewalld_services | length > 0
    )

- name: 'Include tasks to prepare the Satellite installtion'
  ansible.builtin.include_tasks:
    file: 'preparation.yml'
...
